services:
  - type: web
    name: nepal-silver-tracker
    env: node
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
